version: '3'

vars:
  BINARY_NAME: runapp

tasks:
  install-tools:
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
  lint:
    desc: Run lint
    cmds:
      - golangci-lint run ./...
  test:
    desc: Run tests
    deps:
      - build
    cmds:
      - go test -count=1 ./...
  build:
    desc: Build the Go binary
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -o bin/{{.BINARY_NAME}} ./cmd
  build-all:
    desc: Build Go binaries for linux/macos and amd64/arm64
    env:
      CGO_ENABLED: 0
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o release/{{.BINARY_NAME}}-linux-amd64 ./cmd
      - GOOS=linux GOARCH=arm64 go build -o release/{{.BINARY_NAME}}-linux-arm64 ./cmd
      - GOOS=darwin GOARCH=arm64 go build -o release/{{.BINARY_NAME}}-macos-arm64 ./cmd
      - GOOS=darwin GOARCH=amd64 go build -o release/{{.BINARY_NAME}}-macos-amd64 ./cmd
