name: Pull request

on:
  pull_request:
    branches: [main]

jobs:
  pull-requests:
    name: Pull request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install tools
        run: ./bin/task install-tools

      - name: Run Lint
        run: ./bin/task lint

      - name: Run Tests
        run: ./bin/task test

      - name: Run Build all
        run: ./bin/task build-all
